[[data]]
"अङ्गम्" = 'प्लुतान्वितं'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'विकल्पः'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '"सर्व एव प्लुतः साहसमनिच्छता विभाषा कर्त्तव्यः" इति पतञ्जलिः।'
"प्रभावोदाहरणम्" = '''
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''



[[data]]
"अङ्गम्" = 'अशूद्रम् अस्त्रिकं नाम|गोत्रं|भोः'
"प्रत्ययः/ विवक्षा" = 'सम्बोधनं वाक्यान्ते प्रत्यभिवादने'
"परिणामः" = 'टेः प्लुतः (क्वचिद् विकल्पेन)'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'प्रत्यभिवादेऽशूद्रे। (स्त्रियां न। भोराजन्यविशां वेति वाच्यम्।)'
"प्रभावोदाहरणम्" = '''भो आयुष्मान् एधि देवदत्ता꣡ ३ ॥  
विकल्पेन - आयुष्मानेधि भोः3 । आयुष्मानेधीन्द्रवर्म3न् । आयुष्मानेधीन्द्रपालित3 ॥
'''
"अभावोदाहरणम्" = 'आयुष्मानेधि तुषजक। भो आयुष्मती भव गार्गि ॥ आयुष्मानेधि ।'
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'सम्बोधनं दूरात्, वाक्यान्ते'
"परिणामः" = 'टेः प्लुतः (एकश्रुतिः)'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ' दूराद्धूते च'
"प्रभावोदाहरणम्" = '''आगच्छ यज्ञदत्ता ३ ॥  
पलायस्व देवदत्ता ३ ॥
'''
"अभावोदाहरणम्" = 'समीपस्थागच्छ देवदत्त। आगच्छ। '
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'है हे'
"प्रत्ययः/ विवक्षा" = 'सम्बोधनं दूरात्'
"परिणामः" = 'टेः प्लुतः (एकश्रुतिः)'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ' हैहेप्रयोगे हैहयोः'
"प्रभावोदाहरणम्" = '''है ३ देवदत्त।   
 हे ३ देवदत्त। 
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = 'प्लुतान्वितं नाम|गोत्रं'
"प्रत्ययः/ विवक्षा" = 'सम्बोधनं दूरात्'
"परिणामः" = 'कस्यचन गुरोः ॠॡभिन्नस्य प्लुतो विकल्पेन'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'गुरोरनृतोऽनन्त्यस्याप्येकैकस्य प्राचाम्'
"प्रभावोदाहरणम्" = '''हे दे꣡३वदत्त  
देवद꣡३त्त
'''
"अभावोदाहरणम्" = 'कृष्णमि꣡३त्र'
"विवरणम्" = ''



[[data]]
"अङ्गम्" = 'ॐ'
"प्रत्ययः/ विवक्षा" = 'ग्रन्थारम्भे'
"परिणामः" = 'प्लुतः'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'ओमभ्यादाने'
"प्रभावोदाहरणम्" = '''
ओ३म् अ॒॒ग्निमीले॑ पु॒॒रोहि॑तं य॒॒ज्ञस्य॑ दे॒॒वमृ॒॒त्विजं॑ ॥
'''
"अभावोदाहरणम्" = 'ओमित्येतदक्षरमुद्गीथमुपासीत'
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'ये'
"प्रत्ययः/ विवक्षा" = 'यजामहे इत्यस्मात् प्राक् यज्ञे'
"परिणामः" = 'प्लुतः'
"प्रासिद्ध्यम्" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'ये यज्ञकर्मणि'
"प्रभावोदाहरणम्" = '''
ये3 यजामहे।
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''


[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'मन्त्रान्ते यज्ञे'
"परिणामः" = 'टेः ओ३म्'
"प्रासिद्ध्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'प्रणवष् टेः'
"प्रभावोदाहरणम्" = '''
 देवाञ् जिगाति सुम्नयो꣡ ३म् ॥
'''
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

