baseURL = "https://vvasuki.github.io/sanskrit/"
languageCode = "en-us"
title = "संस्कृते विश्वासटिप्पणयः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vvasuki/sanskrit/edit/master/content/"
  contactLink = "https://github.com/vvasuki/sanskrit/issues/new"
  env = "production"
  disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true